// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChzb_5AleOZH3GsFVc5yb6QHRgMBELE-g',
    appId: '1:859571743183:web:3970662a9dd153d5330aba',
    messagingSenderId: '859571743183',
    projectId: 'teamup-usm',
    authDomain: 'teamup-usm.firebaseapp.com',
    storageBucket: 'teamup-usm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE5YlPHSTDpaF25B9F-gT0bDn1XqHZS7Q',
    appId: '1:859571743183:android:b81436c7164d058e330aba',
    messagingSenderId: '859571743183',
    projectId: 'teamup-usm',
    storageBucket: 'teamup-usm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbPMLY0a4QO6lP_O8RQNsPi7KA_OgAADg',
    appId: '1:859571743183:ios:10885cb53566aeaa330aba',
    messagingSenderId: '859571743183',
    projectId: 'teamup-usm',
    storageBucket: 'teamup-usm.firebasestorage.app',
    iosBundleId: 'com.example.teamup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbPMLY0a4QO6lP_O8RQNsPi7KA_OgAADg',
    appId: '1:859571743183:ios:10885cb53566aeaa330aba',
    messagingSenderId: '859571743183',
    projectId: 'teamup-usm',
    storageBucket: 'teamup-usm.firebasestorage.app',
    iosBundleId: 'com.example.teamup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChzb_5AleOZH3GsFVc5yb6QHRgMBELE-g',
    appId: '1:859571743183:web:ba7dee1771aae9b0330aba',
    messagingSenderId: '859571743183',
    projectId: 'teamup-usm',
    authDomain: 'teamup-usm.firebaseapp.com',
    storageBucket: 'teamup-usm.firebasestorage.app',
  );
}
